#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  zworkspace exec <workspace>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local workspace=$1
  local args=${@:2}

  if [ -n "$workspace" ] && [ "$workspace" != "-" ]; then
    local SERVICE_NAME=workspace_user_$workspace
    workspace::notify exec >> /dev/null 2>&1 &

    zmicro service exec $SERVICE_NAME $args
    exit 0
  fi

  local services_path=$ZMICRO_PLUGINS_CONFIGS_PATH/service/config
  if [ ! -d "$services_path" ]; then
    log::info "No workspaces found"
    exit 0
  fi

  local services=$(ls $services_path)

  local workspaces=""
  local count=0
  for service in $services; do
    local workspace_file_path=$ZMICRO_PLUGINS_CONFIGS_PATH/service/config/$service/workspace
    if [ -f "$workspace_file_path" ]; then
      count=$(($count + 1))
      local name=${service#workspace_user_}
      if [ "$workspaces" = "" ]; then
        workspaces=($name)
      else
        workspaces=(${workspaces[@]} $name)
      fi
    fi
  done

  if [ "$count" = "0" ]; then
    log::info "No workspaces found"
    exit 0
  fi

  inquirer::select "Select an workspace ?" workspaces workspace
  local SERVICE_NAME=workspace_user_$workspace

  if [ "$(zmicro service is_running $SERVICE_NAME)" = "false" ]; then
    log::error "workspace $workspace is not running"
    exit 1
  fi

  # local SERVICE_CONFIG_DIR=$ZMICRO_PLUGINS_CONFIGS_PATH/service/config/$workspace
  workspace::notify exec $SERVICE_NAME >> /dev/null 2>&1 &
  
  zmicro service exec $SERVICE_NAME $args
}

run() {
  core $@
}

run $@
