#!/bin/bash

help() {
  echo "Usage:"
  echo "  zworkspace env upgrade"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local role=$role

  workspace::env_upgrade $role
}

run() {
  core $@
}

run $@
